services:
  # app:
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - REDIS_HOST=cache
  #   env_file:
  #     - .env

  db:
    image: postgres:16-alpine
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    container_name: url_shortener_cache
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

  worker:
    build: .
    container_name: url_shortener_worker
    command: python -m app.worker
    depends_on:
      - db
      - cache
    environment:
      - REDIS_HOST=cache
      - DB_HOST=db
      - DB_PORT=5432
    env_file:
      - .env
volumes:
  postgres_data:
